name: CI
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: Sherif
        run: vp run sherif

      - name: Build
        run: vp run build
        env:
          TURBO_TOKEN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.TURBO_TOKEN || '' }}
          TURBO_TEAM: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.TURBO_TEAM || '' }}

      - name: Check
        run: vp check

      - name: Test
        run: vp run test
        env:
          TURBO_TOKEN: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.TURBO_TOKEN || '' }}
          TURBO_TEAM: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.TURBO_TEAM || '' }}
