name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Vite Plus
        uses: voidzero-dev/setup-vp@v1.17.0
        with:
          cache: true
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: |
          vp run --filter "./packages/*" --cache build

      - name: Create Release
        id: changeset
        uses: changesets/action@v2.1.1
        with:
          commit-message: "chore(release): 📦 version packages"
          pr-title: "chore(release): 📦 version packages"
          publish-script: vp run changeset:publish
          version-script: vp run changeset:version
        env:
          npm_config_force: "true"
